### ISSUE TITLE
Enquiry on some experiment results, thx!

### ISSUE THREAD

**Issue by HenryHZY** [jongjyh/glue_ground#1]
Hi @jongjyh , thanks for your great project!
I am unfamiliar with GLUE, but I am interested in parameter-efficient learning.
Just find that you have implemented some models, such as LST-BERT.
Would you mind sharing some experiment results of your models? 
Thanks a lot!

**Comment by HenryHZY** [comment]
Though I mainly focus on multimodal learning. 
But GLUE is really a simple benchmark for the performance testing of parameter-efficient methods:)

**Comment by HenryHZY** [comment]
另外，我快速check了一下，你的LST-BERT的ladder初始化应该是用的 ladder_layer = linear(Transformer_layer)？
如果是的话，从直观上面讲，LST-BERT本质是确实还是通过降维进行初始化。
不过引入更多的linear而非原文的直接剪枝，我觉得Transformer内部的语义信息会有所损失，当然也使得LST-BERT有类似于蒸馏学习的优势。

**Comment by jongjyh** [comment]
> 

是的，我没有引入一整个transformer_module，如果只有一个Linear，在GLUE的MRPC上约有75%的acc（finetuning 89%），我有试过使用整个transformer_module，大概有83%左右的acc（年代久远可能不准确），直觉上看这可能和模型容量有关，越大的模型可能对LST更适配。另外基于`Transformers`的脚本很容易在glue上测试，参见`run_glue.sh` 修改`task_name`就能无缝切换到另外的GLUE数据集。

**Comment by HenryHZY** [comment]
好的，谢谢 @jongjyh 的快速答复：）
我也觉得是跟模型规模有关的，也许更大的模型经过剪枝or可学习的降维，可以更好地保持原始模型的性能，LST-T5原文应该算是一个简单的例子。
